service: rubylingo-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  memorySize: 1024
  timeout: 30
  environment:
    NODE_ENV: production
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!README.md'
    - '!package-lock.json'
    - '!yarn.lock'
    - '!docs/**'
    - '!scripts/**'
    - '!data/**'
    - '!dictionaries/basic.json'
    - '!dictionaries/business.json'
    - '!dictionaries/academic.json'
    - '!dictionaries/comprehensive.json'
    - 'dictionaries/shower/business.json'
    - 'dictionaries/shower/metadata.json'
    - '!dictionaries/shower/academic.json'
    - '!dictionaries/shower/comprehensive.json'
    - '!dictionaries/shower/daily.json'
    - '!*.log'
    - '!*.zip'
    - '!.env*'
    - '!tests/**'
    - '!coverage/**'
    - '!.nyc_output/**'
    - '!.vscode/**'
    - '!.idea/**'
    - '!*.swp'
    - '!*.swo'
    - '!*~'
    - '!.DS_Store'
    - '!archive/**'
    - '!node_modules/lodash/**'

# plugins:
#   - serverless-offline

# custom:
#   serverless-offline:
#     httpPort: 3000
#     lambdaPort: 3001