service: rubylingo-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  stage: ${opt:stage, 'v1'}  # Short stage name: /v1 instead of /production
  memorySize: 2048  # Increased from 1024MB to 2048MB for faster cold starts
  timeout: 60  # Extended from 30s to 60s for longer text processing
  environment:
    NODE_ENV: production
  apiGateway:
    binaryMediaTypes:
      - '*/*'
    # Custom domain configuration (requires domain ownership)
    # domainName: api.rubylingo.com
    # certificateArn: arn:aws:acm:ap-northeast-1:ACCOUNT_ID:certificate/CERT_ID

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
      # Keep warm event to reduce cold starts
      - schedule:
          rate: rate(4 minutes)
          enabled: true
          input:
            warmer: true

package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!README.md'
    - '!package-lock.json'
    - '!yarn.lock'
    - '!docs/**'
    - '!scripts/**'
    - '!data/**'
    - '!dictionaries/basic.json'
    - '!dictionaries/business.json'
    - '!dictionaries/academic.json'
    - '!dictionaries/comprehensive.json'
    - '!dictionaries/shower/**'
    - 'dictionaries/shower/business.json'
    - 'dictionaries/shower/metadata.json'
    - 'node_modules/kuromoji/dict/**'
    - 'node_modules/kuromoji/src/**'
    - '!*.log'
    - '!*.zip'
    - '!.env*'
    - '!tests/**'
    - '!coverage/**'
    - '!.nyc_output/**'
    - '!.vscode/**'
    - '!.idea/**'
    - '!*.swp'
    - '!*.swo'
    - '!*~'
    - '!.DS_Store'
    - '!archive/**'
    - '!node_modules/lodash/**'
    - '!node_modules/**/test/**'
    - '!node_modules/**/tests/**'
    - '!node_modules/**/*.md'

# plugins:
#   - serverless-offline
#   - serverless-domain-manager

custom:
  # Remove stage from URL path
  stage: ${opt:stage, 'prod'}

# Alternative approach for root path without custom domain:
# This requires manual API Gateway configuration after deployment

#   serverless-offline:
#     httpPort: 3000
#     lambdaPort: 3001
#   customDomain:
#     domainName: api.rubylingo.com  # Your custom domain
#     stage: production
#     certificateName: '*.rubylingo.com'
#     createRoute53Record: true
#     endpointType: 'regional'